import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  goldenPathSidebar: [
    "overview",
    {
      type: "category",
      label: "Profiles",
      link: { type: "doc", id: "profiles" },
      items: [
        {
          type: "category",
          label: "Server",
          link: { type: "doc", id: "profiles/server/index" },
          items: ["profiles/server/first-party", "profiles/server/third-party"],
        },
        "profiles/client",
        "profiles/tooling",
        "profiles/schema-designer",
        "profiles/application-developer",
      ],
    },
    {
      type: "category",
      label: "Practices",
      link: { type: "doc", id: "practices" },
      items: [{ type: "autogenerated", dirName: "practices" }],
    },
    {
      type: "category",
      label: "Patterns",
      link: { type: "doc", id: "patterns" },
      items: [{ type: "autogenerated", dirName: "patterns" }],
    },
    {
      type: "category",
      label: "Problems",
      link: { type: "doc", id: "problems" },
      items: [{ type: "autogenerated", dirName: "problems" }],
    },
  ],
};

export default sidebars;
